routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//ckeditor
  Route::resource('/ckeditor', 'ckeditor\ckeditorController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ckeditor/ckeditorController.php
<?php

namespace App\Http\Controllers\ckeditor;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ckeditor\Ckeditor;
use DB;

class ckeditorController extends Controller
{
    //
    public function index(){
      $q = request()->input('q');
      $ckeditors = DB::table('ckeditors')
          ->paginate(5);

      //return view('ckeditor.index');
      return view('ckeditor.index',compact('ckeditors'))
                        ->with('i', (request()->input('page', 1) - 1) * 5);;
    }

    public function store(Request $request){
      $data = ['soal' => $request->soal,
              'jawaban' => $request->jawaban];
      Ckeditor::create($data);

      return redirect()->route('ckeditor.index')
                      ->with('success', 'Simpan berhasil.');
    }
}

resources/views/ckeditor.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Belajar CKEditor</title>
  </head>
  <body>
    <h1>Belajar CKEditor ubah</h1>
    <h6>dimas belajar ckeditor</h6>
  </body>
</html>

resources/views/ckeditor/index.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Belajar CKeditor</title>

    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
  </head>
  <body>
    <div class="container">

      <h1>Belajar CKeditor</h1>
      <h6>Dimas Alamsyah</h6>

      <form action="{{route('ckeditor.store')}}" method="post" style="padding: 15px">
        {{ csrf_field() }}

        @if ($message = Session::get('success'))
          <div class="alert alert-success">
              <p>{{ $message }}</p>
          </div>
        @endif

        <input class="form-control" type="text" name="soal" value="" placeholder="Soal" style="margin-bottom: 15px">
        <textarea class="form-control" name="jawaban" id="editor" rows="8" cols="80" style="margin-bottom: 15px"></textarea>
        <button type="submit" name="button" class="btn btn-success" style="margin-top: 15px">Simpan</button>
      </form>

    <hr>

      @foreach ($ckeditors as $ckeditor)
        <span>{{ ++$i }}.</span>
        <span>{{ $ckeditor->soal }}</span>
        <span>{!! $ckeditor->jawaban !!}</span>
        <br>
      @endforeach

    </div>

  </body>

  <script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
  <script>
      CKEDITOR.replace( 'editor' );
  </script>

</html>